export interface CityGuide {
  citySlug: string;
  guideUrl: string;
  title: string;
  shortTitle: string;
  description: string;
  readTime: string;
  publishDate: string;
  badge?: string;
}

export const CITY_BLOG_GUIDES: Record<string, CityGuide> = {
  // Texas
  'austin': {
    citySlug: 'austin',
    guideUrl: '/blog/indoor-dog-parks-in-austin-tx-top-spots-for-your-pup',
    title: 'Indoor Dog Parks in Austin, TX: Top Spots for Your Pup',
    shortTitle: 'Austin Indoor Dog Parks Editorial Guide',
    description: 'Discover top-rated climate-controlled indoor dog parks, canine agility clubs, and dog bars across Austin to beat the Texas summer heat and flash storms.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'austin-tx': {
    citySlug: 'austin-tx',
    guideUrl: '/blog/indoor-dog-parks-in-austin-tx-top-spots-for-your-pup',
    title: 'Indoor Dog Parks in Austin, TX: Top Spots for Your Pup',
    shortTitle: 'Austin Indoor Dog Parks Editorial Guide',
    description: 'Discover top-rated climate-controlled indoor dog parks, canine agility clubs, and dog bars across Austin to beat the Texas summer heat and flash storms.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'houston': {
    citySlug: 'houston',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-houston',
    title: 'Top 10 Best Indoor Dog Parks in Houston',
    shortTitle: 'Houston Indoor Dog Parks Editorial Guide',
    description: 'Explore Houston’s top climate-controlled indoor dog parks, splash pads, and air-conditioned dog bars designed for intense Gulf Coast humidity.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'houston-tx': {
    citySlug: 'houston-tx',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-houston',
    title: 'Top 10 Best Indoor Dog Parks in Houston',
    shortTitle: 'Houston Indoor Dog Parks Editorial Guide',
    description: 'Explore Houston’s top climate-controlled indoor dog parks, splash pads, and air-conditioned dog bars designed for intense Gulf Coast humidity.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'dallas': {
    citySlug: 'dallas',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-dallas-texas',
    title: 'Top 10 Best Indoor Dog Parks in Dallas, Texas',
    shortTitle: 'Dallas Indoor Dog Parks Editorial Guide',
    description: 'Discover premier indoor dog parks, climate-controlled agility zones, and off-leash dog lounges across the Dallas-Fort Worth metroplex.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'dallas-tx': {
    citySlug: 'dallas-tx',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-dallas-texas',
    title: 'Top 10 Best Indoor Dog Parks in Dallas, Texas',
    shortTitle: 'Dallas Indoor Dog Parks Editorial Guide',
    description: 'Discover premier indoor dog parks, climate-controlled agility zones, and off-leash dog lounges across the Dallas-Fort Worth metroplex.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'corpus-christi': {
    citySlug: 'corpus-christi',
    guideUrl: '/blog/top-8-best-indoor-dog-parks-in-corpus-christi-tx-coastal-bend-guide',
    title: 'Top 8 Best Indoor Dog Parks in Corpus Christi, TX (Coastal Bend Guide)',
    shortTitle: 'Corpus Christi Indoor Dog Parks Guide',
    description: 'Discover the top indoor dog parks, daycares, and climate-controlled play arenas in Corpus Christi, TX to escape Gulf heat and grassburs.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'corpus-christi-tx': {
    citySlug: 'corpus-christi-tx',
    guideUrl: '/blog/top-8-best-indoor-dog-parks-in-corpus-christi-tx-coastal-bend-guide',
    title: 'Top 8 Best Indoor Dog Parks in Corpus Christi, TX (Coastal Bend Guide)',
    shortTitle: 'Corpus Christi Indoor Dog Parks Guide',
    description: 'Discover the top indoor dog parks, daycares, and climate-controlled play arenas in Corpus Christi, TX to escape Gulf heat and grassburs.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'arlington': {
    citySlug: 'arlington',
    guideUrl: '/blog/top-6-best-indoor-dog-parks-and-daycares-in-arlington-tx',
    title: 'Top 6 Best Indoor Dog Parks & Daycares in Arlington, TX',
    shortTitle: 'Arlington Indoor Dog Parks Guide',
    description: 'Explore climate-controlled dog parks and daycares across Arlington and the Mid-Cities for year-round active play.',
    readTime: '7 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'arlington-tx': {
    citySlug: 'arlington-tx',
    guideUrl: '/blog/top-6-best-indoor-dog-parks-and-daycares-in-arlington-tx',
    title: 'Top 6 Best Indoor Dog Parks & Daycares in Arlington, TX',
    shortTitle: 'Arlington Indoor Dog Parks Guide',
    description: 'Explore climate-controlled dog parks and daycares across Arlington and the Mid-Cities for year-round active play.',
    readTime: '7 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'el-paso': {
    citySlug: 'el-paso',
    guideUrl: '/blog/top-5-best-indoor-dog-parks-in-el-paso',
    title: 'Top 5 Best Indoor Dog Parks in El Paso',
    shortTitle: 'El Paso Indoor Dog Parks Guide',
    description: 'Beat West Texas desert heat and dust storms with the top air-conditioned indoor dog play facilities in El Paso.',
    readTime: '7 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'el-paso-tx': {
    citySlug: 'el-paso-tx',
    guideUrl: '/blog/top-5-best-indoor-dog-parks-in-el-paso',
    title: 'Top 5 Best Indoor Dog Parks in El Paso',
    shortTitle: 'El Paso Indoor Dog Parks Guide',
    description: 'Beat West Texas desert heat and dust storms with the top air-conditioned indoor dog play facilities in El Paso.',
    readTime: '7 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },

  // Arizona
  'phoenix': {
    citySlug: 'phoenix',
    guideUrl: '/blog/best-indoor-dog-parks-in-phoenix-your-complete-guide',
    title: 'Best Indoor Dog Parks in Phoenix: Your Complete Guide',
    shortTitle: 'Phoenix Indoor Dog Parks Editorial Guide',
    description: 'Complete guide to surviving 115°F desert summers with air-conditioned indoor dog parks, daycares, and canine agility centers in the Valley of the Sun.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'phoenix-az': {
    citySlug: 'phoenix-az',
    guideUrl: '/blog/best-indoor-dog-parks-in-phoenix-your-complete-guide',
    title: 'Best Indoor Dog Parks in Phoenix: Your Complete Guide',
    shortTitle: 'Phoenix Indoor Dog Parks Editorial Guide',
    description: 'Complete guide to surviving 115°F desert summers with air-conditioned indoor dog parks, daycares, and canine agility centers in the Valley of the Sun.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'mesa': {
    citySlug: 'mesa',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-mesa-az',
    title: 'Top 10 Best Indoor Dog Parks in Mesa, AZ',
    shortTitle: 'Mesa Indoor Dog Parks Guide',
    description: 'Top climate-controlled dog parks and play venues in Mesa and the East Valley to protect paws from blistering pavement.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'mesa-az': {
    citySlug: 'mesa-az',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-mesa-az',
    title: 'Top 10 Best Indoor Dog Parks in Mesa, AZ',
    shortTitle: 'Mesa Indoor Dog Parks Guide',
    description: 'Top climate-controlled dog parks and play venues in Mesa and the East Valley to protect paws from blistering pavement.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'tucson': {
    citySlug: 'tucson',
    guideUrl: '/blog/top-8-best-indoor-dog-parks-in-tucson-a-local-s-guide-to-beating-the-heat',
    title: 'Top 8 Best Indoor Dog Parks in Tucson: A Local’s Guide to Beating the Heat',
    shortTitle: 'Tucson Indoor Dog Parks Guide',
    description: 'A local’s guide to air-conditioned play spaces, dog lounges, and indoor facilities across Tucson and Southern Arizona.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'tucson-az': {
    citySlug: 'tucson-az',
    guideUrl: '/blog/top-8-best-indoor-dog-parks-in-tucson-a-local-s-guide-to-beating-the-heat',
    title: 'Top 8 Best Indoor Dog Parks in Tucson: A Local’s Guide to Beating the Heat',
    shortTitle: 'Tucson Indoor Dog Parks Guide',
    description: 'A local’s guide to air-conditioned play spaces, dog lounges, and indoor facilities across Tucson and Southern Arizona.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },

  // Florida
  'orlando': {
    citySlug: 'orlando',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-orlando-fl-central-florida',
    title: 'Top 10 Best Indoor Dog Parks in Orlando, FL (Central Florida)',
    shortTitle: 'Orlando Indoor Dog Parks Editorial Guide',
    description: 'Discover Central Florida’s premier indoor dog parks, canine agility gyms, and climate-controlled daycares to beat summer thunderstorms and humidity.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'orlando-fl': {
    citySlug: 'orlando-fl',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-orlando-fl-central-florida',
    title: 'Top 10 Best Indoor Dog Parks in Orlando, FL (Central Florida)',
    shortTitle: 'Orlando Indoor Dog Parks Editorial Guide',
    description: 'Discover Central Florida’s premier indoor dog parks, canine agility gyms, and climate-controlled daycares to beat summer thunderstorms and humidity.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'tampa': {
    citySlug: 'tampa',
    guideUrl: '/blog/10-best-indoor-dog-parks-dog-bars-and-daycares-in-tampa-fl',
    title: '10 Best Indoor Dog Parks, Dog Bars & Daycares in Tampa, FL',
    shortTitle: 'Tampa Indoor Dog Parks Guide',
    description: 'Explore Tampa Bay’s best indoor dog play parks, air-conditioned dog bars, and luxury play centers.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'tampa-fl': {
    citySlug: 'tampa-fl',
    guideUrl: '/blog/10-best-indoor-dog-parks-dog-bars-and-daycares-in-tampa-fl',
    title: '10 Best Indoor Dog Parks, Dog Bars & Daycares in Tampa, FL',
    shortTitle: 'Tampa Indoor Dog Parks Guide',
    description: 'Explore Tampa Bay’s best indoor dog play parks, air-conditioned dog bars, and luxury play centers.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'miami': {
    citySlug: 'miami',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-miami-fl-beat-the-heat-and-humidity',
    title: 'Top 10 Best Indoor Dog Parks in Miami, FL: Beat the Heat and Humidity',
    shortTitle: 'Miami Indoor Dog Parks Guide',
    description: 'Beat South Florida heat and monsoon downpours with top indoor play facilities, dog lounges, and air-conditioned dog parks across Miami.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'miami-fl': {
    citySlug: 'miami-fl',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-miami-fl-beat-the-heat-and-humidity',
    title: 'Top 10 Best Indoor Dog Parks in Miami, FL: Beat the Heat and Humidity',
    shortTitle: 'Miami Indoor Dog Parks Guide',
    description: 'Beat South Florida heat and monsoon downpours with top indoor play facilities, dog lounges, and air-conditioned dog parks across Miami.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'jacksonville': {
    citySlug: 'jacksonville',
    guideUrl: '/blog/top-indoor-dog-parks-in-jacksonville-florida',
    title: 'Top Indoor Dog Parks in Jacksonville, Florida',
    shortTitle: 'Jacksonville Indoor Dog Parks Guide',
    description: 'Find verified indoor play spaces and daycares across Jacksonville and Northeast Florida for year-round socialization.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'jacksonville-fl': {
    citySlug: 'jacksonville-fl',
    guideUrl: '/blog/top-indoor-dog-parks-in-jacksonville-florida',
    title: 'Top Indoor Dog Parks in Jacksonville, Florida',
    shortTitle: 'Jacksonville Indoor Dog Parks Guide',
    description: 'Find verified indoor play spaces and daycares across Jacksonville and Northeast Florida for year-round socialization.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },

  // Georgia
  'atlanta': {
    citySlug: 'atlanta',
    guideUrl: '/blog/top-8-best-indoor-dog-parks-in-atlanta-surviving-the-georgia-heat-and-rain',
    title: 'Top 8 Best Indoor Dog Parks in Atlanta: Surviving the Georgia Heat & Rain',
    shortTitle: 'Atlanta Indoor Dog Parks Editorial Guide',
    description: 'Discover the best climate-controlled dog parks, indoor play bars, and daycares in Atlanta and the surrounding metro area.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'atlanta-ga': {
    citySlug: 'atlanta-ga',
    guideUrl: '/blog/top-8-best-indoor-dog-parks-in-atlanta-surviving-the-georgia-heat-and-rain',
    title: 'Top 8 Best Indoor Dog Parks in Atlanta: Surviving the Georgia Heat & Rain',
    shortTitle: 'Atlanta Indoor Dog Parks Editorial Guide',
    description: 'Discover the best climate-controlled dog parks, indoor play bars, and daycares in Atlanta and the surrounding metro area.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },

  // California
  'santa-ana': {
    citySlug: 'santa-ana',
    guideUrl: '/blog/top-8-best-indoor-dog-parks-in-santa-ana-ca',
    title: 'Top 8 Best Indoor Dog Parks in Santa Ana, CA (Orange County Guide)',
    shortTitle: 'Santa Ana Indoor Dog Parks Guide',
    description: 'Discover verified climate-controlled indoor dog parks, canine agility arenas, and daycares across Santa Ana and Central Orange County.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'santa-ana-ca': {
    citySlug: 'santa-ana-ca',
    guideUrl: '/blog/top-8-best-indoor-dog-parks-in-santa-ana-ca',
    title: 'Top 8 Best Indoor Dog Parks in Santa Ana, CA (Orange County Guide)',
    shortTitle: 'Santa Ana Indoor Dog Parks Guide',
    description: 'Discover verified climate-controlled indoor dog parks, canine agility arenas, and daycares across Santa Ana and Central Orange County.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'irvine': {
    citySlug: 'irvine',
    guideUrl: '/blog/top-8-best-indoor-dog-parks-in-irvine-ca-orange-county-guide',
    title: 'Top 8 Best Indoor Dog Parks in Irvine, CA (Orange County Guide)',
    shortTitle: 'Irvine Indoor Dog Parks Guide',
    description: 'Explore verified climate-controlled indoor dog parks, canine agility gyms, and luxury daycares in Irvine to beat the SoCal heat, Santa Ana winds, and foothill foxtails.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'irvine-ca': {
    citySlug: 'irvine-ca',
    guideUrl: '/blog/top-8-best-indoor-dog-parks-in-irvine-ca-orange-county-guide',
    title: 'Top 8 Best Indoor Dog Parks in Irvine, CA (Orange County Guide)',
    shortTitle: 'Irvine Indoor Dog Parks Guide',
    description: 'Explore verified climate-controlled indoor dog parks, canine agility gyms, and luxury daycares in Irvine to beat the SoCal heat, Santa Ana winds, and foothill foxtails.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'anaheim': {
    citySlug: 'anaheim',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-anaheim-ca-orange-county',
    title: 'Top 10 Best Indoor Dog Parks in Anaheim, CA (Orange County)',
    shortTitle: 'Anaheim Indoor Dog Parks Guide',
    description: 'Discover top indoor dog parks and daycares across Anaheim and North Orange County with rubber flooring and live webcams.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'anaheim-ca': {
    citySlug: 'anaheim-ca',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-anaheim-ca-orange-county',
    title: 'Top 10 Best Indoor Dog Parks in Anaheim, CA (Orange County)',
    shortTitle: 'Anaheim Indoor Dog Parks Guide',
    description: 'Discover top indoor dog parks and daycares across Anaheim and North Orange County with rubber flooring and live webcams.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'san-diego': {
    citySlug: 'san-diego',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-san-diego-california',
    title: 'Top 10 Best Indoor Dog Parks in San Diego, California',
    shortTitle: 'San Diego Indoor Dog Parks Guide',
    description: 'Explore the top climate-controlled indoor dog parks, play areas, and daycares across San Diego County.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'san-diego-ca': {
    citySlug: 'san-diego-ca',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-san-diego-california',
    title: 'Top 10 Best Indoor Dog Parks in San Diego, California',
    shortTitle: 'San Diego Indoor Dog Parks Guide',
    description: 'Explore the top climate-controlled indoor dog parks, play areas, and daycares across San Diego County.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'riverside': {
    citySlug: 'riverside',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-riverside-ca-inland-empire',
    title: 'Top 10 Best Indoor Dog Parks in Riverside, CA (Inland Empire)',
    shortTitle: 'Riverside Indoor Dog Parks Guide',
    description: 'Beat the Inland Empire summer heat with the best climate-controlled dog parks and daycares in Riverside.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'riverside-ca': {
    citySlug: 'riverside-ca',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-riverside-ca-inland-empire',
    title: 'Top 10 Best Indoor Dog Parks in Riverside, CA (Inland Empire)',
    shortTitle: 'Riverside Indoor Dog Parks Guide',
    description: 'Beat the Inland Empire summer heat with the best climate-controlled dog parks and daycares in Riverside.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'long-beach': {
    citySlug: 'long-beach',
    guideUrl: '/blog/the-ultimate-guide-to-the-top-10-best-indoor-dog-parks-in-long-beach-ca',
    title: 'The Ultimate Guide to the Top 10 Best Indoor Dog Parks in Long Beach, CA',
    shortTitle: 'Long Beach Indoor Dog Parks Guide',
    description: 'Discover the premier indoor dog parks, canine agility gyms, and play centers in Long Beach, CA.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'long-beach-ca': {
    citySlug: 'long-beach-ca',
    guideUrl: '/blog/the-ultimate-guide-to-the-top-10-best-indoor-dog-parks-in-long-beach-ca',
    title: 'The Ultimate Guide to the Top 10 Best Indoor Dog Parks in Long Beach, CA',
    shortTitle: 'Long Beach Indoor Dog Parks Guide',
    description: 'Discover the premier indoor dog parks, canine agility gyms, and play centers in Long Beach, CA.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'los-angeles': {
    citySlug: 'los-angeles',
    guideUrl: '/blog/top-10-best-doggy-soft-play-areas-in-los-angeles',
    title: 'Top 10 Best Doggy Soft Play Areas in Los Angeles',
    shortTitle: 'Los Angeles Doggy Soft Play Guide',
    description: 'Discover top indoor soft play spaces, daycares, and dog lounges in the Greater Los Angeles area.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'los-angeles-ca': {
    citySlug: 'los-angeles-ca',
    guideUrl: '/blog/top-10-best-doggy-soft-play-areas-in-los-angeles',
    title: 'Top 10 Best Doggy Soft Play Areas in Los Angeles',
    shortTitle: 'Los Angeles Doggy Soft Play Guide',
    description: 'Discover top indoor soft play spaces, daycares, and dog lounges in the Greater Los Angeles area.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'stockton': {
    citySlug: 'stockton',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-stockton-ca-and-the-central-valley',
    title: 'Top 10 Best Indoor Dog Parks in Stockton, CA (and the Central Valley)',
    shortTitle: 'Stockton Indoor Dog Parks Guide',
    description: 'Complete guide to indoor dog parks and climate-controlled boarding in Stockton and the Central Valley.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'stockton-ca': {
    citySlug: 'stockton-ca',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-stockton-ca-and-the-central-valley',
    title: 'Top 10 Best Indoor Dog Parks in Stockton, CA (and the Central Valley)',
    shortTitle: 'Stockton Indoor Dog Parks Guide',
    description: 'Complete guide to indoor dog parks and climate-controlled boarding in Stockton and the Central Valley.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'bakersfield': {
    citySlug: 'bakersfield',
    guideUrl: '/blog/10-best-indoor-dog-parks-and-daycares-in-bakersfield-ca',
    title: '10 Best Indoor Dog Parks & Daycares in Bakersfield, CA',
    shortTitle: 'Bakersfield Indoor Dog Parks Guide',
    description: 'Top air-conditioned play parks and daycares across Bakersfield and Kern County.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'bakersfield-ca': {
    citySlug: 'bakersfield-ca',
    guideUrl: '/blog/10-best-indoor-dog-parks-and-daycares-in-bakersfield-ca',
    title: '10 Best Indoor Dog Parks & Daycares in Bakersfield, CA',
    shortTitle: 'Bakersfield Indoor Dog Parks Guide',
    description: 'Top air-conditioned play parks and daycares across Bakersfield and Kern County.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },

  // Other States
  'new-orleans': {
    citySlug: 'new-orleans',
    guideUrl: '/blog/top-5-best-indoor-dog-parks-in-new-orleans-beat-the-heat-and-rain',
    title: 'Top 5 Best Indoor Dog Parks in New Orleans: Beat the Heat and Rain',
    shortTitle: 'New Orleans Indoor Dog Parks Guide',
    description: 'Beat the Big Easy’s heat and torrential rain with the best indoor dog play facilities in New Orleans.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'new-orleans-la': {
    citySlug: 'new-orleans-la',
    guideUrl: '/blog/top-5-best-indoor-dog-parks-in-new-orleans-beat-the-heat-and-rain',
    title: 'Top 5 Best Indoor Dog Parks in New Orleans: Beat the Heat and Rain',
    shortTitle: 'New Orleans Indoor Dog Parks Guide',
    description: 'Beat the Big Easy’s heat and torrential rain with the best indoor dog play facilities in New Orleans.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'newark': {
    citySlug: 'newark',
    guideUrl: '/blog/top-8-best-indoor-dog-parks-in-newark-nj-and-surrounding-metro-area',
    title: 'Top 8 Best Indoor Dog Parks in Newark, NJ (and Surrounding Metro Area)',
    shortTitle: 'Newark Indoor Dog Parks Guide',
    description: 'Top indoor dog parks and training arenas across Newark and Northern New Jersey.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'newark-nj': {
    citySlug: 'newark-nj',
    guideUrl: '/blog/top-8-best-indoor-dog-parks-in-newark-nj-and-surrounding-metro-area',
    title: 'Top 8 Best Indoor Dog Parks in Newark, NJ (and Surrounding Metro Area)',
    shortTitle: 'Newark Indoor Dog Parks Guide',
    description: 'Top indoor dog parks and training arenas across Newark and Northern New Jersey.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'charlotte': {
    citySlug: 'charlotte',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-charlotte-nc',
    title: 'Top 10 Best Indoor Dog Parks in Charlotte, NC',
    shortTitle: 'Charlotte Indoor Dog Parks Guide',
    description: 'Discover Queen City’s top climate-controlled dog parks, indoor daycares, and dog bars.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'charlotte-nc': {
    citySlug: 'charlotte-nc',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-charlotte-nc',
    title: 'Top 10 Best Indoor Dog Parks in Charlotte, NC',
    shortTitle: 'Charlotte Indoor Dog Parks Guide',
    description: 'Discover Queen City’s top climate-controlled dog parks, indoor daycares, and dog bars.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'indianapolis': {
    citySlug: 'indianapolis',
    guideUrl: '/blog/top-5-best-indoor-dog-parks-in-indianapolis',
    title: 'Top 5 Best Indoor Dog Parks in Indianapolis',
    shortTitle: 'Indianapolis Indoor Dog Parks Guide',
    description: 'Top indoor dog parks and play zones in Indy for winter exercise and rainy-day fun.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'indianapolis-in': {
    citySlug: 'indianapolis-in',
    guideUrl: '/blog/top-5-best-indoor-dog-parks-in-indianapolis',
    title: 'Top 5 Best Indoor Dog Parks in Indianapolis',
    shortTitle: 'Indianapolis Indoor Dog Parks Guide',
    description: 'Top indoor dog parks and play zones in Indy for winter exercise and rainy-day fun.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'cleveland': {
    citySlug: 'cleveland',
    guideUrl: '/blog/top-5-best-indoor-dog-parks-in-cleveland-ohio-a-complete-guide',
    title: 'Top 5 Best Indoor Dog Parks in Cleveland, Ohio: A Complete Guide',
    shortTitle: 'Cleveland Indoor Dog Parks Guide',
    description: 'Escape lake-effect snow and freeze with Cleveland’s best indoor dog gyms and parks.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'cleveland-oh': {
    citySlug: 'cleveland-oh',
    guideUrl: '/blog/top-5-best-indoor-dog-parks-in-cleveland-ohio-a-complete-guide',
    title: 'Top 5 Best Indoor Dog Parks in Cleveland, Ohio: A Complete Guide',
    shortTitle: 'Cleveland Indoor Dog Parks Guide',
    description: 'Escape lake-effect snow and freeze with Cleveland’s best indoor dog gyms and parks.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'washington-dc': {
    citySlug: 'washington-dc',
    guideUrl: '/blog/top-5-best-indoor-dog-parks-in-washington-dc',
    title: 'Top 5 Best Indoor Dog Parks in Washington, DC',
    shortTitle: 'Washington DC Indoor Dog Parks Guide',
    description: 'Top indoor dog parks, agility clubs, and dog bars across the District and DMV area.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'colorado-springs': {
    citySlug: 'colorado-springs',
    guideUrl: '/blog/the-ultimate-guide-to-the-top-10-indoor-dog-parks-in-colorado-springs-co',
    title: 'The Ultimate Guide to the Top 10 Indoor Dog Parks in Colorado Springs, CO',
    shortTitle: 'Colorado Springs Indoor Dog Parks Guide',
    description: 'Year-round indoor dog parks and training facilities across the Pikes Peak region.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'colorado-springs-co': {
    citySlug: 'colorado-springs-co',
    guideUrl: '/blog/the-ultimate-guide-to-the-top-10-indoor-dog-parks-in-colorado-springs-co',
    title: 'The Ultimate Guide to the Top 10 Indoor Dog Parks in Colorado Springs, CO',
    shortTitle: 'Colorado Springs Indoor Dog Parks Guide',
    description: 'Year-round indoor dog parks and training facilities across the Pikes Peak region.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'albuquerque': {
    citySlug: 'albuquerque',
    guideUrl: '/blog/top-7-best-climate-controlled-dog-play-areas-in-albuquerque-nm',
    title: 'Top 7 Best Climate-Controlled Dog Play Areas in Albuquerque, NM',
    shortTitle: 'Albuquerque Indoor Dog Play Guide',
    description: 'Top climate-controlled dog play venues and daycares in Duke City.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'albuquerque-nm': {
    citySlug: 'albuquerque-nm',
    guideUrl: '/blog/top-7-best-climate-controlled-dog-play-areas-in-albuquerque-nm',
    title: 'Top 7 Best Climate-Controlled Dog Play Areas in Albuquerque, NM',
    shortTitle: 'Albuquerque Indoor Dog Play Guide',
    description: 'Top climate-controlled dog play venues and daycares in Duke City.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'tulsa': {
    citySlug: 'tulsa',
    guideUrl: '/blog/9-best-indoor-dog-parks-in-tulsa-where-to-play-rain-or-shine',
    title: '9 Best Indoor Dog Parks in Tulsa: Where to Play Rain or Shine',
    shortTitle: 'Tulsa Indoor Dog Parks Guide',
    description: 'Discover Tulsa’s best indoor dog play areas and daycares for rain or shine fun.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'tulsa-ok': {
    citySlug: 'tulsa-ok',
    guideUrl: '/blog/9-best-indoor-dog-parks-in-tulsa-where-to-play-rain-or-shine',
    title: '9 Best Indoor Dog Parks in Tulsa: Where to Play Rain or Shine',
    shortTitle: 'Tulsa Indoor Dog Parks Guide',
    description: 'Discover Tulsa’s best indoor dog play areas and daycares for rain or shine fun.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'lexington': {
    citySlug: 'lexington',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-lexington-ky-the-bluegrass-guide-to-year-round-play',
    title: 'Top 10 Best Indoor Dog Parks in Lexington, KY: The Bluegrass Guide to Year-Round Play',
    shortTitle: 'Lexington Indoor Dog Parks Guide',
    description: 'Bluegrass guide to the best indoor dog parks, daycares, and training facilities in Lexington.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'lexington-ky': {
    citySlug: 'lexington-ky',
    guideUrl: '/blog/top-10-best-indoor-dog-parks-in-lexington-ky-the-bluegrass-guide-to-year-round-play',
    title: 'Top 10 Best Indoor Dog Parks in Lexington, KY: The Bluegrass Guide to Year-Round Play',
    shortTitle: 'Lexington Indoor Dog Parks Guide',
    description: 'Bluegrass guide to the best indoor dog parks, daycares, and training facilities in Lexington.',
    readTime: '9 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'honolulu': {
    citySlug: 'honolulu',
    guideUrl: '/blog/the-top-5-best-indoor-dog-parks-and-playgrounds-in-honolulu',
    title: 'The Top 5 Best Indoor Dog Parks & Playgrounds in Honolulu',
    shortTitle: 'Honolulu Indoor Dog Parks Guide',
    description: 'Explore top indoor dog playgrounds and daycare lounges across Oahu and Honolulu.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
  'honolulu-hi': {
    citySlug: 'honolulu-hi',
    guideUrl: '/blog/the-top-5-best-indoor-dog-parks-and-playgrounds-in-honolulu',
    title: 'The Top 5 Best Indoor Dog Parks & Playgrounds in Honolulu',
    shortTitle: 'Honolulu Indoor Dog Parks Guide',
    description: 'Explore top indoor dog playgrounds and daycare lounges across Oahu and Honolulu.',
    readTime: '8 min read',
    publishDate: 'August 2026',
    badge: 'Featured Local Guide',
  },
};

export function getCityGuide(slug: string): CityGuide | null {
  if (!slug) return null;
  const normalized = slug.toLowerCase().trim();
  return CITY_BLOG_GUIDES[normalized] || null;
}

export interface StateGuideItem {
  citySlug: string;
  cityName: string;
  guideUrl: string;
  title: string;
  shortTitle: string;
  description: string;
  readTime: string;
  badge?: string;
}

export const STATE_BLOG_GUIDES: Record<string, StateGuideItem[]> = {
  'texas': [
    {
      citySlug: 'austin',
      cityName: 'Austin',
      guideUrl: '/blog/indoor-dog-parks-in-austin-tx-top-spots-for-your-pup',
      title: 'Indoor Dog Parks in Austin, TX: Top Spots for Your Pup',
      shortTitle: 'Austin Guide',
      description: 'Discover top-rated climate-controlled indoor dog parks, canine agility clubs, and dog bars across Austin.',
      readTime: '8 min read',
      badge: 'Austin Guide',
    },
    {
      citySlug: 'houston',
      cityName: 'Houston',
      guideUrl: '/blog/top-10-best-indoor-dog-parks-in-houston',
      title: 'Top 10 Best Indoor Dog Parks in Houston',
      shortTitle: 'Houston Guide',
      description: 'Explore Houston’s top climate-controlled indoor dog parks, splash pads, and air-conditioned dog bars.',
      readTime: '9 min read',
      badge: 'Houston Guide',
    },
    {
      citySlug: 'dallas',
      cityName: 'Dallas',
      guideUrl: '/blog/top-10-best-indoor-dog-parks-in-dallas-texas',
      title: 'Top 10 Best Indoor Dog Parks in Dallas, Texas',
      shortTitle: 'Dallas Guide',
      description: 'Premier indoor dog parks, climate-controlled agility zones, and off-leash lounges across DFW.',
      readTime: '9 min read',
      badge: 'Dallas Guide',
    },
    {
      citySlug: 'corpus-christi',
      cityName: 'Corpus Christi',
      guideUrl: '/blog/top-8-best-indoor-dog-parks-in-corpus-christi-tx-coastal-bend-guide',
      title: 'Top 8 Best Indoor Dog Parks in Corpus Christi, TX',
      shortTitle: 'Corpus Christi Guide',
      description: 'Discover top indoor dog parks and play arenas in Corpus Christi to escape Gulf heat and grassburs.',
      readTime: '8 min read',
      badge: 'Coastal Bend Guide',
    },
    {
      citySlug: 'arlington',
      cityName: 'Arlington',
      guideUrl: '/blog/top-6-best-indoor-dog-parks-and-daycares-in-arlington-tx',
      title: 'Top 6 Best Indoor Dog Parks & Daycares in Arlington, TX',
      shortTitle: 'Arlington Guide',
      description: 'Explore climate-controlled dog parks and daycares across Arlington and the Mid-Cities.',
      readTime: '7 min read',
      badge: 'Arlington Guide',
    },
    {
      citySlug: 'el-paso',
      cityName: 'El Paso',
      guideUrl: '/blog/top-5-best-indoor-dog-parks-in-el-paso',
      title: 'Top 5 Best Indoor Dog Parks in El Paso',
      shortTitle: 'El Paso Guide',
      description: 'Air-conditioned indoor dog play facilities in El Paso to beat desert heat.',
      readTime: '7 min read',
      badge: 'El Paso Guide',
    },
  ],
  'california': [
    {
      citySlug: 'santa-ana',
      cityName: 'Santa Ana',
      guideUrl: '/blog/top-8-best-indoor-dog-parks-in-santa-ana-ca',
      title: 'Top 8 Best Indoor Dog Parks in Santa Ana, CA (Orange County Guide)',
      shortTitle: 'Santa Ana Guide',
      description: 'Explore climate-controlled dog parks and daycares across Santa Ana and Central Orange County.',
      readTime: '9 min read',
      badge: 'Orange County Guide',
    },
    {
      citySlug: 'irvine',
      cityName: 'Irvine',
      guideUrl: '/blog/top-8-best-indoor-dog-parks-in-irvine-ca-orange-county-guide',
      title: 'Top 8 Best Indoor Dog Parks in Irvine, CA (Orange County Guide)',
      shortTitle: 'Irvine Guide',
      description: 'Explore verified climate-controlled indoor dog parks and canine agility gyms in Irvine.',
      readTime: '8 min read',
      badge: 'Orange County Guide',
    },
    {
      citySlug: 'anaheim',
      cityName: 'Anaheim',
      guideUrl: '/blog/top-10-best-indoor-dog-parks-in-anaheim-ca-orange-county',
      title: 'Top 10 Best Indoor Dog Parks in Anaheim, CA',
      shortTitle: 'Anaheim Guide',
      description: 'Discover top indoor dog parks and daycares across Anaheim and North Orange County.',
      readTime: '9 min read',
      badge: 'Anaheim Guide',
    },
    {
      citySlug: 'san-diego',
      cityName: 'San Diego',
      guideUrl: '/blog/top-10-best-indoor-dog-parks-in-san-diego-california',
      title: 'Top 10 Best Indoor Dog Parks in San Diego, California',
      shortTitle: 'San Diego Guide',
      description: 'Top climate-controlled indoor dog parks, play areas, and daycares across San Diego County.',
      readTime: '8 min read',
      badge: 'San Diego Guide',
    },
    {
      citySlug: 'riverside',
      cityName: 'Riverside',
      guideUrl: '/blog/top-10-best-indoor-dog-parks-in-riverside-ca-inland-empire',
      title: 'Top 10 Best Indoor Dog Parks in Riverside, CA (Inland Empire)',
      shortTitle: 'Riverside Guide',
      description: 'Beat the Inland Empire summer heat with top climate-controlled dog parks in Riverside.',
      readTime: '8 min read',
      badge: 'Inland Empire Guide',
    },
    {
      citySlug: 'long-beach',
      cityName: 'Long Beach',
      guideUrl: '/blog/the-ultimate-guide-to-the-top-10-best-indoor-dog-parks-in-long-beach-ca',
      title: 'Top 10 Best Indoor Dog Parks in Long Beach, CA',
      shortTitle: 'Long Beach Guide',
      description: 'Premier indoor dog parks, canine agility gyms, and play centers in Long Beach.',
      readTime: '8 min read',
      badge: 'Long Beach Guide',
    },
    {
      citySlug: 'los-angeles',
      cityName: 'Los Angeles',
      guideUrl: '/blog/top-10-best-doggy-soft-play-areas-in-los-angeles',
      title: 'Top 10 Best Doggy Soft Play Areas in Los Angeles',
      shortTitle: 'Los Angeles Guide',
      description: 'Top indoor soft play spaces, daycares, and dog lounges in Greater Los Angeles.',
      readTime: '8 min read',
      badge: 'Los Angeles Guide',
    },
    {
      citySlug: 'stockton',
      cityName: 'Stockton',
      guideUrl: '/blog/top-10-best-indoor-dog-parks-in-stockton-ca-and-the-central-valley',
      title: 'Top 10 Best Indoor Dog Parks in Stockton, CA',
      shortTitle: 'Stockton Guide',
      description: 'Indoor dog parks and climate-controlled boarding in Stockton and the Central Valley.',
      readTime: '8 min read',
      badge: 'Central Valley Guide',
    },
    {
      citySlug: 'bakersfield',
      cityName: 'Bakersfield',
      guideUrl: '/blog/10-best-indoor-dog-parks-and-daycares-in-bakersfield-ca',
      title: '10 Best Indoor Dog Parks & Daycares in Bakersfield, CA',
      shortTitle: 'Bakersfield Guide',
      description: 'Air-conditioned play parks and daycares across Bakersfield and Kern County.',
      readTime: '8 min read',
      badge: 'Bakersfield Guide',
    },
  ],
  'florida': [
    {
      citySlug: 'orlando',
      cityName: 'Orlando',
      guideUrl: '/blog/top-10-best-indoor-dog-parks-in-orlando-fl-central-florida',
      title: 'Top 10 Best Indoor Dog Parks in Orlando, FL',
      shortTitle: 'Orlando Guide',
      description: 'Central Florida premier indoor dog parks, agility gyms, and daycares.',
      readTime: '9 min read',
      badge: 'Orlando Guide',
    },
    {
      citySlug: 'tampa',
      cityName: 'Tampa',
      guideUrl: '/blog/10-best-indoor-dog-parks-dog-bars-and-daycares-in-tampa-fl',
      title: '10 Best Indoor Dog Parks, Dog Bars & Daycares in Tampa, FL',
      shortTitle: 'Tampa Guide',
      description: 'Tampa Bay indoor dog play parks, air-conditioned dog bars, and play centers.',
      readTime: '9 min read',
      badge: 'Tampa Guide',
    },
    {
      citySlug: 'miami',
      cityName: 'Miami',
      guideUrl: '/blog/top-10-best-indoor-dog-parks-in-miami-fl-beat-the-heat-and-humidity',
      title: 'Top 10 Best Indoor Dog Parks in Miami, FL',
      shortTitle: 'Miami Guide',
      description: 'Beat South Florida heat with top indoor play facilities and dog lounges in Miami.',
      readTime: '9 min read',
      badge: 'Miami Guide',
    },
    {
      citySlug: 'jacksonville',
      cityName: 'Jacksonville',
      guideUrl: '/blog/top-indoor-dog-parks-in-jacksonville-florida',
      title: 'Top Indoor Dog Parks in Jacksonville, Florida',
      shortTitle: 'Jacksonville Guide',
      description: 'Verified indoor play spaces and daycares across Jacksonville and Northeast Florida.',
      readTime: '8 min read',
      badge: 'Jacksonville Guide',
    },
  ],
  'arizona': [
    {
      citySlug: 'phoenix',
      cityName: 'Phoenix',
      guideUrl: '/blog/best-indoor-dog-parks-in-phoenix-your-complete-guide',
      title: 'Best Indoor Dog Parks in Phoenix: Complete Guide',
      shortTitle: 'Phoenix Guide',
      description: 'Survive desert summers with air-conditioned indoor dog parks in Phoenix.',
      readTime: '9 min read',
      badge: 'Phoenix Guide',
    },
    {
      citySlug: 'mesa',
      cityName: 'Mesa',
      guideUrl: '/blog/top-10-best-indoor-dog-parks-in-mesa-az',
      title: 'Top 10 Best Indoor Dog Parks in Mesa, AZ',
      shortTitle: 'Mesa Guide',
      description: 'Climate-controlled dog parks in Mesa and the East Valley.',
      readTime: '8 min read',
      badge: 'Mesa Guide',
    },
    {
      citySlug: 'tucson',
      cityName: 'Tucson',
      guideUrl: '/blog/top-8-best-indoor-dog-parks-in-tucson-a-local-s-guide-to-beating-the-heat',
      title: 'Top 8 Best Indoor Dog Parks in Tucson',
      shortTitle: 'Tucson Guide',
      description: 'Air-conditioned play spaces and dog lounges across Tucson.',
      readTime: '8 min read',
      badge: 'Tucson Guide',
    },
  ],
};

// Aliases for state abbreviations
STATE_BLOG_GUIDES['tx'] = STATE_BLOG_GUIDES['texas'];
STATE_BLOG_GUIDES['ca'] = STATE_BLOG_GUIDES['california'];
STATE_BLOG_GUIDES['fl'] = STATE_BLOG_GUIDES['florida'];
STATE_BLOG_GUIDES['az'] = STATE_BLOG_GUIDES['arizona'];

export function getStateGuides(slug: string): StateGuideItem[] {
  if (!slug) return [];
  const normalized = slug.toLowerCase().trim();
  return STATE_BLOG_GUIDES[normalized] || [];
}

import fs from 'fs';
import path from 'path';

export function getCityGuideHtml(slug: string): string | null {
  if (!slug) return null;
  const baseSlug = slug.toLowerCase().replace(/-[a-z]{2}$/, '').trim();

  const fileMapping: Record<string, string> = {
    'santa-ana': 'top-8-best-indoor-dog-parks-in-santa-ana-ca.md',
    'corpus-christi': 'top-8-best-indoor-dog-parks-in-corpus-christi-tx.md',
    'anaheim': 'top-10-best-indoor-dog-parks-in-anaheim.md',
    'orlando': 'top-10-best-indoor-dog-parks-in-orlando.md',
    'riverside': 'top-10-best-indoor-dog-parks-in-riverside-ca.md',
    'stockton': 'top-10-best-indoor-dog-parks-in-stockton-ca.md',
    'honolulu': 'top-5-indoor-dog-parks-honolulu.md',
    'islip': 'top-5-indoor-dog-parks-islip.md',
    'new-orleans': 'top-5-indoor-dog-parks-new-orleans.md',
    'irvine': 'top-8-best-indoor-dog-parks-in-irvine-ca.md',
    'newark': 'top-8-best-indoor-dog-parks-in-newark-nj.md',
    'lexington': 'top-10-best-indoor-dog-parks-in-lexington-ky.md',
  };

  const filename = fileMapping[baseSlug] || fileMapping[slug.toLowerCase()];
  if (!filename) return null;

  try {
    const filePath = path.join(process.cwd(), 'blog-content', filename);
    if (!fs.existsSync(filePath)) return null;

    const raw = fs.readFileSync(filePath, 'utf8');
    const body = raw.replace(/^---[\s\S]*?---\n/, '').trim();

    return markdownToProseHtml(body);
  } catch (err) {
    console.error('Error reading city guide content for ' + slug, err);
    return null;
  }
}

function markdownToProseHtml(markdown: string): string {
  // First extract html blocks
  let processed = markdown.replace(/```html\n([\s\S]*?)```/gim, '$1');

  return processed
    .replace(/^# (.*$)/gim, '<h2 class="text-2xl font-bold text-gray-900 mb-4">$1</h2>')
    .replace(/^## (.*$)/gim, '<h3 class="text-xl font-bold text-gray-900 mt-8 mb-4 border-b border-gray-200 pb-2">$1</h3>')
    .replace(/^### (.*$)/gim, '<h4 class="text-lg font-bold text-gray-900 mt-6 mb-2">$1</h4>')
    .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/gim, '<em>$1</em>')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/gim, '<a href="$2" class="text-emerald-600 hover:text-emerald-800 underline font-medium">$1</a>')
    .replace(/^\* (.*$)/gim, '<li class="ml-4 list-disc text-gray-700 my-1">$1</li>')
    .replace(/^- (.*$)/gim, '<li class="ml-4 list-disc text-gray-700 my-1">$1</li>')
    .replace(/^(\d+)\. (.*$)/gim, '<li class="ml-4 list-decimal text-gray-700 my-1">$2</li>');
}

