name = "indoordogpark"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

# Bindings required for OpenNext
# https://opennext.js.org/cloudflare

[vars]
DATA_BASE_URL = "https://new-indoordogpark.pages.dev"
NEXT_PUBLIC_DATA_BASE_URL = "https://new-indoordogpark.pages.dev"
# Environment variables will be set in Cloudflare dashboard
